"use strict"

Object.defineProperty(exports, "__esModule", {
  value: true,
})
var data = [
  {
    questionType: "greetings",
    answerType: "None",
    koDescription: "Hi~ I'm P-BOT to get survey for OOO employees life 😀",
    enDescription: "",
    dashboardDescription: "",
    order: 1,
    image: null,
    questionSubtype: null,
    id: 1153,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [],
  },
  {
    questionType: "greetings",
    answerType: "None",
    koDescription:
      "I am a chatbot developed by the HR Analytics company Chatbot, and we will regularly hear from our employees.",
    enDescription: "",
    dashboardDescription: "",
    order: 2,
    image: null,
    questionSubtype: null,
    id: 1154,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [],
  },
  {
    questionType: "greetings",
    answerType: "None",
    koDescription: "Thank you very much~😉",
    enDescription: "",
    dashboardDescription: "",
    order: 3,
    image: null,
    questionSubtype: null,
    id: 1155,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [],
  },
  {
    questionType: "greetings",
    answerType: "Multiple Choice",
    koDescription:
      "The answer is thoroughly anonymous, so please give a frank answer. Time required is less than 3 minutes. Can I get started right away?",
    enDescription: "",
    dashboardDescription: "",
    order: 4,
    image: null,
    questionSubtype: null,
    id: 1156,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Remind",
        answerType: "Multiple Choice",
        koDescription: "Yes, please choose a comfortable time!😊",
        enDescription: "",
        dashboardDescription: "",
        order: 1,
        image: null,
        questionSubtype: "",
        id: 1170,
        surveyId: 11,
        parentId: 1156,
        choices: [
          {
            koDescription: "1 hour later",
            enDescription: "",
            order: 1,
            score: 0,
            subquestion: 2,
            id: 3761,
            questionId: 1170,
          },
          {
            koDescription: "3 hour later",
            enDescription: "",
            order: 2,
            score: 0,
            subquestion: 2,
            id: 3762,
            questionId: 1170,
          },
          {
            koDescription: "Tomorrow",
            enDescription: "",
            order: 3,
            score: 0,
            subquestion: 2,
            id: 3763,
            questionId: 1170,
          },
        ],
      },
      {
        questionType: "termination",
        answerType: "None",
        koDescription: "I'll meet you on time.~🤗",
        enDescription: "",
        dashboardDescription: "",
        order: 2,
        image: null,
        questionSubtype: "",
        id: 1171,
        surveyId: 11,
        parentId: 1156,
        choices: [],
      },
    ],
    choices: [
      {
        koDescription: "👌 Start",
        enDescription: "",
        order: 1,
        score: 0,
        subquestion: null,
        id: 3701,
        questionId: 1156,
      },
      {
        koDescription: "Let me know it again later~",
        enDescription: "",
        order: 2,
        score: 0,
        subquestion: 1,
        id: 3702,
        questionId: 1156,
      },
    ],
  },
  {
    questionType: "greetings",
    answerType: "None",
    koDescription:
      "Please remind yourself of the experiences you have had in your last month~",
    enDescription: "",
    dashboardDescription: "",
    order: 5,
    image: null,
    questionSubtype: null,
    id: 1157,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [],
  },
  {
    questionType: "Work-life Balance",
    answerType: "Emoji Rating",
    koDescription:
      "Do you think the balance of work and life in the past month has been appropriate?",
    enDescription: "",
    dashboardDescription:
      "I think the balance of my work and life in the past month has been appropriate.",
    order: 6,
    image: null,
    questionSubtype: "",
    id: 1158,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Normal",
        answerType: "Multiple Choice",
        koDescription: "How many hours have you worked overtime this month?",
        enDescription: "",
        dashboardDescription: "Average overtime per day",
        order: 1,
        image: null,
        questionSubtype: "Overtime",
        id: 1172,
        surveyId: 11,
        parentId: 1158,
        choices: [
          {
            koDescription: "Less than 1 hour",
            enDescription: "",
            order: 1,
            score: 1,
            subquestion: null,
            id: 3764,
            questionId: 1172,
          },
          {
            koDescription: "1-2 hours",
            enDescription: "",
            order: 2,
            score: 2,
            subquestion: null,
            id: 3765,
            questionId: 1172,
          },
          {
            koDescription: "2-3 hours",
            enDescription: "",
            order: 3,
            score: 3,
            subquestion: 2,
            id: 3766,
            questionId: 1172,
          },
          {
            koDescription: "More than 3 hours",
            enDescription: "",
            order: 4,
            score: 4,
            subquestion: 3,
            id: 3767,
            questionId: 1172,
          },
        ],
      },
      {
        questionType: "greetings",
        answerType: "None",
        koDescription: "😨",
        enDescription: "",
        dashboardDescription: "",
        order: 2,
        image: null,
        questionSubtype: null,
        id: 1173,
        surveyId: 11,
        parentId: 1158,
        choices: [],
      },
      {
        questionType: "greetings",
        answerType: "None",
        koDescription: "😱",
        enDescription: "",
        dashboardDescription: "",
        order: 3,
        image: null,
        questionSubtype: null,
        id: 1174,
        surveyId: 11,
        parentId: 1158,
        choices: [],
      },
    ],
    choices: [
      {
        koDescription: "😡",
        enDescription: "😡",
        order: 1,
        score: 20,
        subquestion: 1,
        id: 3703,
        questionId: 1158,
      },
      {
        koDescription: "😠",
        enDescription: "😠",
        order: 2,
        score: 40,
        subquestion: 1,
        id: 3704,
        questionId: 1158,
      },
      {
        koDescription: "😐",
        enDescription: "😐",
        order: 3,
        score: 60,
        subquestion: 1,
        id: 3705,
        questionId: 1158,
      },
      {
        koDescription: "😏",
        enDescription: "😏",
        order: 4,
        score: 80,
        subquestion: 0,
        id: 3706,
        questionId: 1158,
      },
      {
        koDescription: "😃",
        enDescription: "😃",
        order: 5,
        score: 100,
        subquestion: 0,
        id: 3707,
        questionId: 1158,
      },
    ],
  },
  {
    questionType: "Meaningful Work",
    answerType: "Likert",
    koDescription:
      "How did you feel about the last month's work? Was it worth it enough?",
    enDescription: "",
    dashboardDescription: "I think the work I did was valuable.",
    order: 7,
    image: null,
    questionSubtype: "",
    id: 1159,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Normal",
        answerType: "Multiple Choice",
        koDescription: "What makes you feel that your work is not worth it? 😥",
        enDescription: "",
        dashboardDescription: "Why business value is low",
        order: 1,
        image: null,
        questionSubtype: "Important business value",
        id: 1175,
        surveyId: 11,
        parentId: 1159,
        choices: [
          {
            koDescription: "Unproductive work",
            enDescription: "",
            order: 1,
            score: 1,
            subquestion: null,
            id: 3781,
            questionId: 1175,
          },
          {
            koDescription: "Unnecessary work",
            enDescription: "",
            order: 2,
            score: 2,
            subquestion: null,
            id: 3782,
            questionId: 1175,
          },
          {
            koDescription: "Unacceptable work",
            enDescription: "",
            order: 3,
            score: 3,
            subquestion: null,
            id: 3784,
            questionId: 1175,
          },
          {
            koDescription: "Things that do not fit my capacity",
            enDescription: "",
            order: 4,
            score: 4,
            subquestion: null,
            id: 3783,
            questionId: 1175,
          },
          {
            koDescription: "Other",
            enDescription: "",
            order: 5,
            score: 5,
            subquestion: null,
            id: 3785,
            questionId: 1175,
          },
        ],
      },
    ],
    choices: [
      {
        koDescription: "Very Unworthiness",
        enDescription: "",
        order: 1,
        score: 20,
        subquestion: 1,
        id: 3708,
        questionId: 1159,
      },
      {
        koDescription: "Unworthiness",
        enDescription: "",
        order: 2,
        score: 40,
        subquestion: 1,
        id: 3709,
        questionId: 1159,
      },
      {
        koDescription: "Normal",
        enDescription: "",
        order: 3,
        score: 60,
        subquestion: 1,
        id: 3710,
        questionId: 1159,
      },
      {
        koDescription: "Worthiness",
        enDescription: "",
        order: 4,
        score: 80,
        subquestion: null,
        id: 3711,
        questionId: 1159,
      },
      {
        koDescription: "Very Worthiness",
        enDescription: "",
        order: 5,
        score: 100,
        subquestion: null,
        id: 3712,
        questionId: 1159,
      },
    ],
  },
  {
    questionType: "Mental Wellness",
    answerType: "Emoji Rating",
    koDescription:
      "Overall, how was your mental condition during the past month?",
    enDescription: "",
    dashboardDescription: "My mental health status in the past month",
    order: 8,
    image: null,
    questionSubtype: "",
    id: 1160,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [
      {
        koDescription: "😡",
        enDescription: "😡",
        order: 1,
        score: 20,
        subquestion: null,
        id: 3713,
        questionId: 1160,
      },
      {
        koDescription: "😠",
        enDescription: "😠",
        order: 2,
        score: 40,
        subquestion: null,
        id: 3714,
        questionId: 1160,
      },
      {
        koDescription: "😐",
        enDescription: "😐",
        order: 3,
        score: 60,
        subquestion: null,
        id: 3722,
        questionId: 1160,
      },
      {
        koDescription: "😏",
        enDescription: "😏",
        order: 4,
        score: 80,
        subquestion: null,
        id: 3715,
        questionId: 1160,
      },
      {
        koDescription: "😃",
        enDescription: "😃",
        order: 5,
        score: 100,
        subquestion: null,
        id: 3716,
        questionId: 1160,
      },
    ],
  },
  {
    questionType: "Leadership",
    answerType: "Star Rating",
    koDescription:
      "Do you think your boss now shows effective leadership for his role?",
    enDescription: "",
    dashboardDescription:
      "My boss thinks that it shows effective leadership for the role.",
    order: 9,
    image: null,
    questionSubtype: "",
    id: 1161,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Normal",
        answerType: "Multiple Choice",
        koDescription: "What parts do you feel needing supplementation?",
        enDescription: "",
        dashboardDescription: "Areas requiring development",
        order: 1,
        image: null,
        questionSubtype: "Leadership Improvements",
        id: 1178,
        surveyId: 11,
        parentId: 1161,
        choices: [
          {
            koDescription: "Coaching / Feedback",
            enDescription: "",
            order: 1,
            score: 0,
            subquestion: null,
            id: 3774,
            questionId: 1178,
          },
          {
            koDescription: "Motivation",
            enDescription: "",
            order: 2,
            score: 1,
            subquestion: null,
            id: 3775,
            questionId: 1178,
          },
          {
            koDescription: "Fairness",
            enDescription: "",
            order: 3,
            score: 2,
            subquestion: null,
            id: 3776,
            questionId: 1178,
          },
          {
            koDescription: "Respect / consideration",
            enDescription: "",
            order: 4,
            score: 3,
            subquestion: null,
            id: 3777,
            questionId: 1178,
          },
          {
            koDescription: "problem solving",
            enDescription: "",
            order: 5,
            score: 4,
            subquestion: null,
            id: 3778,
            questionId: 1178,
          },
          {
            koDescription: "Indication",
            enDescription: "",
            order: 6,
            score: 5,
            subquestion: null,
            id: 3779,
            questionId: 1178,
          },
          {
            koDescription: "Other",
            enDescription: "",
            order: 7,
            score: 6,
            subquestion: null,
            id: 3780,
            questionId: 1178,
          },
        ],
      },
      {
        questionType: "greetings",
        answerType: "None",
        koDescription: "👍",
        enDescription: "",
        dashboardDescription: "",
        order: 2,
        image: null,
        questionSubtype: null,
        id: 1176,
        surveyId: 11,
        parentId: 1161,
        choices: [],
      },
    ],
    choices: [
      {
        koDescription: "1",
        enDescription: "1",
        order: 1,
        score: 20,
        subquestion: 1,
        id: 3717,
        questionId: 1161,
      },
      {
        koDescription: "2",
        enDescription: "2",
        order: 2,
        score: 40,
        subquestion: 1,
        id: 3718,
        questionId: 1161,
      },
      {
        koDescription: "3",
        enDescription: "3",
        order: 3,
        score: 60,
        subquestion: 1,
        id: 3719,
        questionId: 1161,
      },
      {
        koDescription: "4",
        enDescription: "4",
        order: 4,
        score: 80,
        subquestion: 2,
        id: 3720,
        questionId: 1161,
      },
      {
        koDescription: "5",
        enDescription: "5",
        order: 5,
        score: 100,
        subquestion: 2,
        id: 3721,
        questionId: 1161,
      },
    ],
  },
  {
    questionType: "Turnover Intention",
    answerType: "Likert",
    koDescription: "Have you ever thought about leaving the last month?",
    enDescription: "",
    dashboardDescription:
      "I have been thinking about leaving or leaving for the last month.",
    order: 10,
    image: null,
    questionSubtype: "",
    id: 1152,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Normal",
        answerType: "Multiple Choice",
        koDescription: "What are the main reasons for that?",
        enDescription: "",
        dashboardDescription: "Reasons for this retirement idea",
        order: 1,
        image: null,
        questionSubtype: "Reasons for leaving work",
        id: 1169,
        surveyId: 11,
        parentId: 1152,
        choices: [
          {
            koDescription: "Work related",
            enDescription: "",
            order: 1,
            score: 1,
            subquestion: null,
            id: 3754,
            questionId: 1169,
          },
          {
            koDescription: "Career Vision",
            enDescription: "",
            order: 2,
            score: 2,
            subquestion: null,
            id: 3755,
            questionId: 1169,
          },
          {
            koDescription: "Boss related",
            enDescription: "",
            order: 3,
            score: 3,
            subquestion: null,
            id: 3756,
            questionId: 1169,
          },
          {
            koDescription: "Compensation related",
            enDescription: "",
            order: 4,
            score: 4,
            subquestion: null,
            id: 3757,
            questionId: 1169,
          },
          {
            koDescription: "HR system issues",
            enDescription: "",
            order: 5,
            score: 5,
            subquestion: null,
            id: 3758,
            questionId: 1169,
          },
          {
            koDescription: "Work-life balance",
            enDescription: "",
            order: 6,
            score: 6,
            subquestion: null,
            id: 3759,
            questionId: 1169,
          },
          {
            koDescription: "Other",
            enDescription: "",
            order: 7,
            score: 7,
            subquestion: null,
            id: 3760,
            questionId: 1169,
          },
        ],
      },
    ],
    choices: [
      {
        koDescription: "Not at all",
        enDescription: "",
        order: 1,
        score: 20,
        subquestion: null,
        id: 3696,
        questionId: 1152,
      },
      {
        koDescription: "Almost none",
        enDescription: "",
        order: 2,
        score: 40,
        subquestion: null,
        id: 3697,
        questionId: 1152,
      },
      {
        koDescription: "Sometimes",
        enDescription: "",
        order: 3,
        score: 60,
        subquestion: 1,
        id: 3698,
        questionId: 1152,
      },
      {
        koDescription: "Frequent",
        enDescription: "",
        order: 4,
        score: 80,
        subquestion: 1,
        id: 3699,
        questionId: 1152,
      },
      {
        koDescription: "Very often",
        enDescription: "",
        order: 5,
        score: 100,
        subquestion: 1,
        id: 3700,
        questionId: 1152,
      },
    ],
  },
  {
    questionType: "Enabler",
    answerType: "Emoji Rating",
    koDescription:
      "Is your team or company providing effective support so you can do your job better now?",
    enDescription: "",
    dashboardDescription:
      "I think that effective support is being provided by the team and the company so that I can do my job better.",
    order: 11,
    image: null,
    questionSubtype: "",
    id: 1162,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Normal",
        answerType: "Multiple Choice",
        koDescription: "Which part do you think needs improvement?",
        enDescription: "",
        dashboardDescription: "Area to improve",
        order: 1,
        image: null,
        questionSubtype: "Support complaint",
        id: 1177,
        surveyId: 11,
        parentId: 1162,
        choices: [
          {
            koDescription: "Workforce reinforcement",
            enDescription: "",
            order: 1,
            score: 1,
            subquestion: null,
            id: 3768,
            questionId: 1177,
          },
          {
            koDescription: "Equipment / Systems",
            enDescription: "",
            order: 2,
            score: 2,
            subquestion: null,
            id: 3769,
            questionId: 1177,
          },
          {
            koDescription: "System / Process",
            enDescription: "",
            order: 3,
            score: 3,
            subquestion: null,
            id: 3770,
            questionId: 1177,
          },
          {
            koDescription: "Organizational structure",
            enDescription: "",
            order: 4,
            score: 4,
            subquestion: null,
            id: 3771,
            questionId: 1177,
          },
          {
            koDescription: "R&R",
            enDescription: "",
            order: 5,
            score: 5,
            subquestion: null,
            id: 3772,
            questionId: 1177,
          },
          {
            koDescription: "Others",
            enDescription: "",
            order: 6,
            score: 6,
            subquestion: null,
            id: 3773,
            questionId: 1177,
          },
        ],
      },
      {
        questionType: "greetings",
        answerType: "None",
        koDescription: "👍",
        enDescription: "",
        dashboardDescription: "",
        order: 2,
        image: null,
        questionSubtype: null,
        id: 1179,
        surveyId: 11,
        parentId: 1162,
        choices: [],
      },
    ],
    choices: [
      {
        koDescription: "😡",
        enDescription: "😡",
        order: 1,
        score: 20,
        subquestion: 1,
        id: 3733,
        questionId: 1162,
      },
      {
        koDescription: "😠",
        enDescription: "😠",
        order: 2,
        score: 40,
        subquestion: 1,
        id: 3734,
        questionId: 1162,
      },
      {
        koDescription: "😐",
        enDescription: "😐",
        order: 3,
        score: 60,
        subquestion: 1,
        id: 3735,
        questionId: 1162,
      },
      {
        koDescription: "😏",
        enDescription: "😏",
        order: 4,
        score: 80,
        subquestion: 2,
        id: 3736,
        questionId: 1162,
      },
      {
        koDescription: "😃",
        enDescription: "😃",
        order: 5,
        score: 100,
        subquestion: 2,
        id: 3737,
        questionId: 1162,
      },
    ],
  },
  {
    questionType: "Recognition",
    answerType: "Emoji Rating",
    koDescription:
      "Do you think you've received enough recognition from your boss or colleague about what you did well in the last month?",
    enDescription: "",
    dashboardDescription:
      "I think I got enough recognition from my boss or colleague about what I did well in the past month.",
    order: 12,
    image: null,
    questionSubtype: "",
    id: 1163,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [
      {
        koDescription: "😡",
        enDescription: "😡",
        order: 1,
        score: 20,
        subquestion: null,
        id: 3723,
        questionId: 1163,
      },
      {
        koDescription: "😠",
        enDescription: "😠",
        order: 2,
        score: 40,
        subquestion: null,
        id: 3732,
        questionId: 1163,
      },
      {
        koDescription: "😐",
        enDescription: "😐",
        order: 3,
        score: 60,
        subquestion: null,
        id: 3724,
        questionId: 1163,
      },
      {
        koDescription: "😏",
        enDescription: "😏",
        order: 4,
        score: 80,
        subquestion: null,
        id: 3725,
        questionId: 1163,
      },
      {
        koDescription: "😃",
        enDescription: "😃",
        order: 5,
        score: 100,
        subquestion: null,
        id: 3726,
        questionId: 1163,
      },
    ],
  },
  {
    questionType: "Empowerment",
    answerType: "Emoji Rating",
    koDescription:
      "Do you think you have been given enough autonomy and authority to perform your work over the last month?",
    enDescription: "",
    dashboardDescription:
      "I think I have been given enough autonomy and authority to carry out my work over the past month.",
    order: 13,
    image: null,
    questionSubtype: "",
    id: 1164,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [
      {
        koDescription: "😡",
        enDescription: "😡",
        order: 1,
        score: 20,
        subquestion: null,
        id: 3727,
        questionId: 1164,
      },
      {
        koDescription: "😠",
        enDescription: "😠",
        order: 2,
        score: 40,
        subquestion: null,
        id: 3728,
        questionId: 1164,
      },
      {
        koDescription: "😐",
        enDescription: "😐",
        order: 3,
        score: 60,
        subquestion: null,
        id: 3729,
        questionId: 1164,
      },
      {
        koDescription: "😏",
        enDescription: "😏",
        order: 4,
        score: 80,
        subquestion: null,
        id: 3730,
        questionId: 1164,
      },
      {
        koDescription: "😃",
        enDescription: "😃",
        order: 5,
        score: 100,
        subquestion: null,
        id: 3731,
        questionId: 1164,
      },
    ],
  },
  {
    questionType: "Growth",
    answerType: "Likert",
    koDescription:
      "Do you feel that there is a high possibility of personal growth in the company now?",
    enDescription: "",
    dashboardDescription:
      "I think the growth potential of the company is great now.",
    order: 14,
    image: null,
    questionSubtype: "",
    id: 1165,
    surveyId: 11,
    parentId: null,
    subquestions: [
      {
        questionType: "Normal",
        answerType: "Multiple Choice",
        koDescription: "Why do you think growth is unlikely?",
        enDescription: "",
        dashboardDescription: "Why you think growth potential is low",
        order: 1,
        image: null,
        questionSubtype: "Growth inhibition factor",
        id: 1180,
        surveyId: 11,
        parentId: 1165,
        choices: [
          {
            koDescription: "Lack of career opportunity",
            enDescription: "",
            order: 1,
            score: 1,
            subquestion: null,
            id: 3786,
            questionId: 1180,
          },
          {
            koDescription: "Inadequate education development",
            enDescription: "",
            order: 2,
            score: 2,
            subquestion: null,
            id: 3787,
            questionId: 1180,
          },
          {
            koDescription: "Lack of employment stability",
            enDescription: "",
            order: 3,
            score: 3,
            subquestion: null,
            id: 3788,
            questionId: 1180,
          },
          {
            koDescription: "HR operational justice",
            enDescription: "",
            order: 4,
            score: 4,
            subquestion: null,
            id: 3789,
            questionId: 1180,
          },
          {
            koDescription: "Other",
            enDescription: "",
            order: 5,
            score: 5,
            subquestion: null,
            id: 3790,
            questionId: 1180,
          },
        ],
      },
      {
        questionType: "greetings",
        answerType: "None",
        koDescription: "👍",
        enDescription: "",
        dashboardDescription: "",
        order: 2,
        image: null,
        questionSubtype: null,
        id: 1181,
        surveyId: 11,
        parentId: 1165,
        choices: [],
      },
    ],
    choices: [
      {
        koDescription: "It is not very",
        enDescription: "",
        order: 1,
        score: 20,
        subquestion: 1,
        id: 3738,
        questionId: 1165,
      },
      {
        koDescription: "Not like that",
        enDescription: "",
        order: 2,
        score: 40,
        subquestion: 1,
        id: 3739,
        questionId: 1165,
      },
      {
        koDescription: "Nomal",
        enDescription: "",
        order: 3,
        score: 60,
        subquestion: 1,
        id: 3740,
        questionId: 1165,
      },
      {
        koDescription: "Yes",
        enDescription: "",
        order: 4,
        score: 80,
        subquestion: 2,
        id: 3741,
        questionId: 1165,
      },
      {
        koDescription: "It really is",
        enDescription: "",
        order: 5,
        score: 100,
        subquestion: 2,
        id: 3742,
        questionId: 1165,
      },
    ],
  },
  {
    questionType: "eNPS",
    answerType: "Slider",
    koDescription:
      "If you have a friend who is looking for a job, are you willing to recommend our company?",
    enDescription: "",
    dashboardDescription:
      "I am willing to recommend my company to a friend or friend who is looking for a job.",
    order: 15,
    image: null,
    questionSubtype: "",
    id: 1166,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [
      {
        koDescription: "Never",
        enDescription: "",
        order: 1,
        score: 0,
        subquestion: null,
        id: 3743,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 2,
        score: 1,
        subquestion: null,
        id: 3744,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 3,
        score: 2,
        subquestion: null,
        id: 3752,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 4,
        score: 3,
        subquestion: null,
        id: 3745,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 5,
        score: 4,
        subquestion: null,
        id: 3746,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 6,
        score: 5,
        subquestion: null,
        id: 3747,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 7,
        score: 6,
        subquestion: null,
        id: 3748,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 8,
        score: 7,
        subquestion: null,
        id: 3749,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 9,
        score: 8,
        subquestion: null,
        id: 3750,
        questionId: 1166,
      },
      {
        koDescription: "",
        enDescription: "",
        order: 10,
        score: 9,
        subquestion: null,
        id: 3751,
        questionId: 1166,
      },
      {
        koDescription: "Highly",
        enDescription: "",
        order: 11,
        score: 10,
        subquestion: null,
        id: 3753,
        questionId: 1166,
      },
    ],
  },
  {
    questionType: "Open-ended",
    answerType: "Comment",
    koDescription:
      "Finally, if you have any suggestions for your company, please fill it free. 🧞",
    enDescription: "",
    dashboardDescription: "In addition, I want to leave the company comment",
    order: 16,
    image: null,
    questionSubtype: "Suggestion",
    id: 1167,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [],
  },
  {
    questionType: "termination",
    answerType: "None",
    koDescription: "Thank you for participating.",
    enDescription: "",
    dashboardDescription: "",
    order: 17,
    image: "79RM6MH5J6VA5724054F2GT8SRLC703FD62I.gif",
    questionSubtype: "",
    id: 1168,
    surveyId: 11,
    parentId: null,
    subquestions: [],
    choices: [],
  },
]

exports.default = data
